resources:
  - alertmanager-alertmanager.yaml
  - alertmanager-secret.yaml
  - alertmanager-serviceAccount.yaml
  - alertmanager-serviceMonitor.yaml
  - alertmanager-service.yaml
  - grafana-dashboardDatasources.yaml
  - grafana-dashboardDefinitions.yaml
  - grafana-dashboardSources.yaml
  - grafana-deployment.yaml
  - grafana-serviceAccount.yaml
  - grafana-serviceMonitor.yaml
  - grafana-service.yaml
  - kube-state-metrics-clusterRoleBinding.yaml
  - kube-state-metrics-clusterRole.yaml
  - kube-state-metrics-deployment.yaml
  - kube-state-metrics-roleBinding.yaml
  - kube-state-metrics-role.yaml
  - kube-state-metrics-serviceAccount.yaml
  - kube-state-metrics-serviceMonitor.yaml
  - kube-state-metrics-service.yaml
  - node-exporter-clusterRoleBinding.yaml
  - node-exporter-clusterRole.yaml
  - node-exporter-daemonset.yaml
  - node-exporter-serviceAccount.yaml
  - node-exporter-serviceMonitor.yaml
  - node-exporter-service.yaml
  - prometheus-adapter-apiService.yaml
  - prometheus-adapter-clusterRoleAggregatedMetricsReader.yaml
  - prometheus-adapter-clusterRoleBindingDelegator.yaml
  - prometheus-adapter-clusterRoleBinding.yaml
  - prometheus-adapter-clusterRoleServerResources.yaml
  - prometheus-adapter-clusterRole.yaml
  - prometheus-adapter-configMap.yaml
  - prometheus-adapter-deployment.yaml
  - prometheus-adapter-roleBindingAuthReader.yaml
  - prometheus-adapter-serviceAccount.yaml
  - prometheus-adapter-service.yaml
  - prometheus-clusterRoleBinding.yaml
  - prometheus-clusterRole.yaml
  - prometheus-operator-serviceMonitor.yaml
  - prometheus-prometheus.yaml
  - prometheus-roleBindingConfig.yaml
  - prometheus-roleBindingSpecificNamespaces.yaml
  - prometheus-roleConfig.yaml
  - prometheus-roleSpecificNamespaces.yaml
  - prometheus-rules.yaml
  - prometheus-serviceAccount.yaml
  - prometheus-serviceMonitorApiserver.yaml
  - prometheus-serviceMonitorCoreDNS.yaml
  - prometheus-serviceMonitorKubeControllerManager.yaml
  - prometheus-serviceMonitorKubelet.yaml
  - prometheus-serviceMonitorKubeScheduler.yaml
  - prometheus-serviceMonitor.yaml
  - prometheus-service.yaml
